WebUI/Controllers/PropertyController.cs
using Business.Services;
using Core.CustomExceptions;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebUI.Controllers
{
    [Authorize]
    public class PropertyController : Controller
    {
        private readonly IPropertyTableService _propertyTableService;
        private readonly IProductPropertyTableService _productPropertyTableService;
        public PropertyController(IPropertyTableService propertyTableService, IProductPropertyTableService productPropertyTableService)
        {
            _propertyTableService = propertyTableService;
            _productPropertyTableService = productPropertyTableService;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["propertys"] = await _propertyTableService.GetListAsync();
            return View();
        }


        public IActionResult AddProperty()
        {
            return View();
        }

        public async Task<IActionResult> AddPropertyMethod(string key, string value)
        {
            try
            {
                var res = await _propertyTableService.AddOrUpdateAsync(new PropertyTableDto() { Key = key, Value = value });
                if (res != null && res.Value != null)
                {
                    return RedirectToAction("Success", "Result");
                }
                else
                {
                    return RedirectToAction("Error", "Result");
                }
            }
            catch
            {
                return RedirectToAction("Error", "Result", new { message = BusinessExceptionMessage.General });
            }
        }

        public async Task<IActionResult> DeleteProperty(Guid id)
        {
            try
            {

                var result = await _productPropertyTableService.GetListAsync(x => x.PropertyId == id);
                var model = await _propertyTableService.GetByIdAsync(id);

                if (model != null && result.Count == 0)
                {

                    await _propertyTableService.DeleteAsync(model);
                    return RedirectToAction("Success", "Result");

                }
                else
                {
                    return RedirectToAction("Error", "Result", new { message = "This feature is actively used" });
                }

            }
            catch
            {
                return RedirectToAction("Error", "Result", new { message = BusinessExceptionMessage.General });
            }

        }
        public async Task<IActionResult> UpdateProperty(Guid id)
        {
            var res = await _propertyTableService.GetByIdAsync(id);
            return View(res);
        }

        public async Task<IActionResult> UpdatePropertyMethod(PropertyTableDto propertyTableDto)
        {
            try
            {
                var res = await _propertyTableService.AddOrUpdateAsync(propertyTableDto);
                if (res != null && res.Value != null)
                {
                    return RedirectToAction("Success", "Result");
                }
                else
                {
                    return RedirectToAction("Error", "Result");
                }
            }
            catch
            {
                return RedirectToAction("Error", "Result", new { message = BusinessExceptionMessage.General });
            }
        }
    }
}

WebUI/Views/Property/AddProperty.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form asp-controller="Property" asp-action="AddPropertyMethod" method="POST">

    <div class="formContainer">

        <img class="imgPrvt" src="/image/add.png" style="margin-bottom: 23px;">

        <div style="display: flex;">

            <input class="inputForm" name="key" placeholder="Özellik" required>

            <input class="inputForm" name="value" placeholder="Açıklama" required>

        </div>

        <button class="buttonPrvt" type="submit" style="margin-bottom: 25px;"> Add Property </button>

    </div>

</form>

WebUI/Views/Property/Index.cshtml
@using Entities.Concrete
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@foreach (var item in (List<PropertyTableDto>)ViewData["propertys"])
{
    <div class="listContainerThere"
         style="border-bottom: 5px solid #9cfc02;border-left: 5px solid #1dffec;border-top: 5px solid #9cfc02;border-right: 5px solid #1dffec;">


        <h2 class="listContainerTitle"> @item.Key </h2>


        <div class="listContainerInThree">

            <div>

                <p class="lisContainerP">Özellik Açıklaması : @item.Value</p>

                <div>

                    <button class="deleteButton" onclick="deleteProperty('@item.Id')">
                        Delete
                    </button>

                    <button class="updateButton" onclick="updateProperty('@item.Id')">
                        Update
                    </button>


                </div>

            </div>
        </div>

    </div>
}

<script>

    async function deleteProperty(propertyId) {
    // Swal onay penceresini göster
    const result = await Swal.fire({
        title: 'Are you sure?',
        text: 'Do you really want to delete this property?',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!',
        cancelButtonText: 'No, cancel!'
    });

    // Kullanıcı onay verdiyse, yönlendirme işlemini gerçekleştir
    if (result.isConfirmed) {
        // Yönlendirme URL'sini oluştur
        const redirectUrl = `/Property/DeleteProperty?id=${propertyId}`;

        // Kullanıcıyı yönlendir
        window.location.href = redirectUrl;
    }
    }

    async function updateProperty(propertyId){
        const redirectUrl = `/Property/UpdateProperty?id=${propertyId}`;

        // Kullanıcıyı yönlendir
        window.location.href = redirectUrl;
    }
</script>

WebUI/Views/Property/UpdateProperty.cshtml
@using Entities.Concrete
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model PropertyTableDto

<form asp-controller="Property" asp-action="UpdatePropertyMethod" method="POST">

    <div class="formContainer">

        <img class="imgPrvt" src="/image/system-update.png" style="margin-bottom: 23px;">

        <div style="display: flex;">

            <input class="inputForm" name="key" value="@Model.Key" placeholder="Özellik" required>

            <input class="inputForm" name="value" value="@Model.Value" placeholder="Açıklama" required>

        </div>

        <button class="buttonPrvt" type="submit" style="margin-bottom: 25px;"> Update Property </button>

    </div>

    <input style="display:none" name="Id" value="@Model.Id" />

    <input style="display:none" name="CreatedDate" value="@Model.CreatedDate" />

    <input style="display:none" name="CreatorUserId" value="@Model.CreatorUserId" />

    <input style="display:none" name="IsDeleted" value="@Model.IsDeleted" />

</form>